"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar/Navbar";
import Footer from "@/components/layout/footer/Footer";
import { Toaster } from 'react-hot-toast';
import { useEffect } from "react";
import { TRPCReactProvider } from "@/trpc/react";

const inter = Inter({ subsets: ["latin"] });
 const metadata: Metadata = {
  title: "Urstyle",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
 }: Readonly<{
  children: React.ReactNode;
 }>) {
  return (
     <html>
       <head>
       </head>
       <body>
       <TRPCReactProvider>
       <div className={inter.className}>{children}</div>
      </TRPCReactProvider>
       </body>
     </html>
  );
 }
 
 



// import Navbar from "@/components/layout/navbar/Navbar";
// import Footer from "@/components/layout/footer/Footer";
 
// export default function Layout({ children }: { children: React.ReactNode }) {
  
//     return (
//      <html>
//         <body>
//           <Navbar/>
//           {children}
//           <Footer/>
//        </body>
//      </html>
//    )
//   }
  
